lidar_topic: /velodyne_points
map_folder: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/new"
map_file: "GlobalMap.pcd"
objects: ["person", "cell phone", "chair", "bench", "tv"]
#map_file: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/new/GlobalMap.pcd"
#object_file: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/objects.txt"
publish_odom_tf: true
num_particles: 2000
alpha_v: 5.0
alpha_w: 0.2
lidar:
  R: [1.0, 0.0, 0.0,
    0.0, 1.0, 0.0,
    0.0, 0.0, 1.0]
  t: [0.0, 0.0, 0.4]

imu_preintegration:
  enable: true
  imu_topic: imu/data
  R: [1.0, 0.0, 0.0,
    0.0, 1.0, 0.0,
    0.0, 0.0, 1.0]
  t: [0.0, 0.0, 0.0]

odom_topic: jackal_velocity_controller/odom # if disable the imu_preintegration
camera:
  enable: true
  R: [0.0, 0.0, 1.0,
    -1.0, 0.0, 0.0,
    0.0, -1.0, 0.0]
  t: [0.0, 0.0, 0.5]
  K: [674.7141017105704, 0.0, 640.5, 0.0, 674.7141017105704, 360.5, 0.0, 0.0, 1.0]