lidar_topic: /points_degen
map_folder: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/new"
map_file: "GlobalMap.pcd"
objects: ["person", "cell phone", "chair", "bench", "tv"]
#map_file: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/new/GlobalMap.pcd"
#object_file: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/objects.txt"
publish_odom_tf: true
num_particles: 2000
alpha_v: 3.0
alpha_w: 2.0
imu_preintegration:
  enable: true
  imu_topic: imu/data
odom_topic: jackal_velocity_controller/odom # if disable the imu_preintegration
camera:
  enable: true
  R: [0.0, 0.0, 1.0,
    -1.0, 0.0, 0.0,
    0.0, -1.0, 0.0]
  t: [0.0, 0.0, 0.5]
  K: [528.433756558705, 0.0, 320.5, 0.0, 528.433756558705, 240.5, 0.0, 0.0, 1.0]