lidar_topic: /velodyne_points
map_file: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/GlobalMap.pcd"
object_file: "/home/nuninu98/catkin_ws/src/LIO-SAM-Semantic/maps/objects.txt"
publish_odom_tf: true
num_particles: 2000
alpha_v: 3.0
alpha_w: 2.0
imu_preintegration:
  enable: true
  imu_topic: imu/data
odom_topic: jackal_velocity_controller/odom # if disable the imu_preintegration